const assert = require('node:assert/strict');
const { planAllocation } = require('../assets/dividend-allocation.js');
const base = { budget: 10000, invested: 0, percent: 20, interval: 30, today: '2026-10-10', lastBuy: '', eligible: true, riskConfirmed: true };
assert.equal(planAllocation(base).amount, 2000);
assert.equal(planAllocation({ ...base, invested: 9500, lastBuy: '2026-08-01' }).amount, 500);
assert.equal(planAllocation({ ...base, invested: 10000 }).state, 'blocked');
assert.equal(planAllocation({ ...base, invested: -1 }).state, 'blocked');
assert.equal(planAllocation({ ...base, invested: 1 }).state, 'blocked');
assert.equal(planAllocation({ ...base, invested: 2000, lastBuy: '2026-10-01' }).state, 'blocked');
assert.equal(planAllocation({ ...base, invested: 2000, lastBuy: '2026-09-10' }).state, 'ready');
assert.equal(planAllocation({ ...base, lastBuy: '2026-10-11' }).state, 'blocked');
assert.equal(planAllocation({ ...base, lastBuy: '2026-02-30' }).state, 'blocked');
assert.equal(planAllocation({ ...base, riskConfirmed: false }).amount, 0);
assert.equal(planAllocation({ ...base, eligible: false }).amount, 0);
assert.equal(planAllocation({ ...base, budget: '' }).state, 'blocked');
assert.equal(planAllocation({ ...base, invested: '' }).state, 'blocked');
assert.equal(planAllocation({ ...base, budget: Infinity }).state, 'blocked');
assert.equal(planAllocation({ ...base, percent: 101 }).state, 'blocked');
console.log('15 allocation-budget and cooldown checks passed');
